name = "MiniFB"
uuid = "cc649173-1898-4bb8-8a16-ca5f88bd87d9"
authors = ["Avik Sengupta"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
